#!/usr/bin/env node
// Builds the canonical Rune 2.0 schema, src/lib/supabase/schema.sql.
//
//   npm --prefix tools/sync-harness run schema           # write schema.sql
//   npm --prefix tools/sync-harness run schema -- --check  # exit 1 if stale
//   npm --prefix tools/sync-harness run schema -- --catalog <file.json>
//       also writes the catalog of the built database, to compare a real
//       Rune 2.0 database against with tools/db-audit/diff-catalog.mjs
//       (--expect schema-only)
//
// Recipe: the Rune 1.x production baseline
// (src/lib/supabase/baseline/production-2026-09-24.sql), then every migration
// numbered 013 and above in order, applied in PGlite behind the Supabase shim;
// the result is captured with tools/db-audit/catalog.sql and written out by
// the same generator as the baseline. The file therefore contains exactly what
// the migrations produce, never a hand edit, and records every migration it
// contains in public.schema_migrations.
//
// tests/rune2-schema.test.mjs proves that schema.sql is current, and that a
// database built from it alone is structurally identical to baseline + migrations.
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { createTestDb, readRepoFile, REPO_DIR, LEGACY_BASELINE, RUNE2_SCHEMA } from './lib/pg.mjs';
import { catalogFromRows } from '../db-audit/catalog-lib.mjs';
import { generateSchemaSql } from '../db-audit/schema-generator.mjs';

const BASELINE_PATH = LEGACY_BASELINE;
const SCHEMA_PATH = RUNE2_SCHEMA;
const MIGRATIONS_DIR = 'src/lib/supabase/migrations';

/** Migration files applied on top of the baseline: 013 and above, in order. */
export function migrationsAfterBaseline() {
  return fs.readdirSync(path.join(REPO_DIR, MIGRATIONS_DIR))
    .filter((f) => /^\d{3}_.*\.sql$/.test(f) && Number(f.slice(0, 3)) >= 13)
    .sort();
}

export const RUNE2_NOTES = {
  manuscripts: [
    'Exactly one per Project (unique project_id), created by trg_project_manuscript',
    'and deleted with the Project. Writers can read their own; nothing else.',
  ],
  chapters: [
    'Ordered manuscript structure. Belongs to a Manuscript (manuscript_id); its',
    'Project is manuscripts.project_id. Contains no prose.',
  ],
  scenes: [
    'Manuscript prose. A Scene BELONGS to one Manuscript (manuscript_id, never',
    'changes) and is PLACED in a Chapter of that Manuscript, or Unplaced when',
    'chapter_id is null. There is no canonical Scene. Scene IDs are stable: a',
    'future Rune 1.x migration keeps every Page ID as its Scene ID.',
  ],
  writing_sessions: [
    'Typed-word writing activity. Editor rows are keyed per Scene (scene_id),',
    'Arena and other rows have scene_id null; uniqueness is the partial unique',
    'indexes below. Deleting a Scene deletes its rows (as in Rune 1.x).',
  ],
  subscription_events: [
    'NOTE: production shape (stripe_event_id NOT NULL, tier, status; no payload)',
    'differs from migration 004 and from what the Stripe webhook inserts, so those',
    'inserts currently fail. Carried over from the Rune 1.x baseline as-is.',
  ],
  'fn:account_word_total': [
    'Free-limit account total: EVERY Scene the caller owns, placed or Unplaced.',
    'Not the ordered manuscript total (placed Scenes only). Never collapse them.',
  ],
  'fn:increment_game_ticket': [
    'Unused by the app. SECURITY DEFINER without a pinned search_path, trusts',
    'p_user_id, and is executable by PUBLIC/anon. Carried over from the Rune 1.x',
    'baseline as-is; hardening is a separate, explicitly approved change.',
  ],
  'fn:save_scene_checked': [
    'Save-path RPC. Statuses: ok | word_limit_blocked | version_mismatch | error',
    '(\'Scene not found\'). Once clients depend on it, never overload or extend it.',
  ],
  'policies:legacy': [
    'projects still carries the legacy "Users can manage their own projects" FOR',
    'ALL policy beside its per-command policies (both permissive, OR-ed), as in',
    'Rune 1.x. Manuscript tables use per-command policies for `authenticated` only.',
  ],
};

function header(migrations) {
  const first = migrations[0].slice(0, 3);
  const last = migrations[migrations.length - 1].slice(0, 3);
  return [
    'Rune 2.0 — canonical schema (GENERATED — do not edit by hand)',
    '',
    'Generated by tools/sync-harness/build-schema.mjs: the Rune 1.x production',
    `baseline (${BASELINE_PATH})`,
    `plus migrations ${first}–${last}, applied in PostgreSQL (PGlite) behind the Supabase`,
    'shim and captured with tools/db-audit/catalog.sql.',
    '',
    'Builds a brand-new Rune 2.0 database in one step. The migrations it contains',
    'are recorded in public.schema_migrations at the end; apply only migrations',
    'numbered above the last one recorded. Migrations 001–012 must never be run.',
    '',
    'Manuscript model: projects → manuscripts (1:1) → chapters → scenes.',
    'A Scene belongs to its Manuscript and is placed in a Chapter or Unplaced',
    '(chapter_id null). There are no manuscript Pages and no canonical Scenes.',
    '',
    'Prerequisite: a Supabase project (roles anon/authenticated/service_role,',
    'auth.users, auth.uid()/auth.role(), and Supabase\'s default privileges).',
    'Supabase-managed objects (extensions, the platform\'s rls_auto_enable event',
    'trigger) are intentionally not created here.',
    '',
    'To change the schema: write a new numbered migration, then regenerate this',
    'file with `npm --prefix tools/sync-harness run schema`.',
  ];
}

/** Captures tools/db-audit/catalog.sql from a database. */
export async function captureCatalog(db) {
  const res = await db.exec(readRepoFile('tools/db-audit/catalog.sql'));
  return catalogFromRows(res[res.length - 1].rows);
}

/** A fresh PGlite database holding the baseline plus every migration from 013. */
export async function migratedDb() {
  const db = await createTestDb();
  await db.exec(readRepoFile(BASELINE_PATH));
  for (const f of migrationsAfterBaseline()) await db.exec(readRepoFile(`${MIGRATIONS_DIR}/${f}`));
  return db;
}

/** Builds the Rune 2.0 schema text from baseline + migrations. */
export async function buildRune2Schema() {
  const migrations = migrationsAfterBaseline();
  const db = await migratedDb();
  const catalog = await captureCatalog(db);
  const ledger = (await db.query(`select version, name, note from public.schema_migrations order by version`)).rows;
  const { sql, stats } = generateSchemaSql(catalog, { header: header(migrations), notes: RUNE2_NOTES, ledger });
  await db.close();
  return { sql, stats, catalog, ledger };
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const check = process.argv.includes('--check');
  const catalogIdx = process.argv.indexOf('--catalog');
  const { sql, stats, catalog } = await buildRune2Schema();
  if (catalogIdx > 0) {
    const file = process.argv[catalogIdx + 1];
    if (!file) { console.error('--catalog needs a file path'); process.exit(2); }
    fs.writeFileSync(file, JSON.stringify(catalog, null, 1));
    console.log(`wrote the built database's catalog to ${file}`);
  }
  const out = path.join(REPO_DIR, SCHEMA_PATH);
  if (check) {
    const current = fs.existsSync(out) ? fs.readFileSync(out, 'utf8') : '';
    if (current !== sql) {
      console.error(`${SCHEMA_PATH} is stale: run \`npm --prefix tools/sync-harness run schema\``);
      process.exit(1);
    }
    console.log(`${SCHEMA_PATH} is current`);
  } else {
    fs.writeFileSync(out, sql);
    console.log(`wrote ${SCHEMA_PATH}: ${stats.tables} tables, ${stats.constraints} constraints, ${stats.functions} functions, ${stats.policies} policies, ${stats.triggers} triggers`);
  }
}
