-- ═══════════════════════════════════════════════════════════════════════════
--  Rune 2.0 — canonical schema (GENERATED — do not edit by hand)
-- ═══════════════════════════════════════════════════════════════════════════
--
--  Generated by tools/sync-harness/build-schema.mjs: the Rune 1.x production
--  baseline (src/lib/supabase/baseline/production-2026-09-24.sql)
--  plus migrations 013–016, applied in PostgreSQL (PGlite) behind the Supabase
--  shim and captured with tools/db-audit/catalog.sql.
--
--  Builds a brand-new Rune 2.0 database in one step. The migrations it contains
--  are recorded in public.schema_migrations at the end; apply only migrations
--  numbered above the last one recorded. Migrations 001–012 must never be run.
--
--  Manuscript model: projects → manuscripts (1:1) → chapters → scenes.
--  A Scene belongs to its Manuscript and is placed in a Chapter or Unplaced
--  (chapter_id null). There are no manuscript Pages and no canonical Scenes.
--
--  Prerequisite: a Supabase project (roles anon/authenticated/service_role,
--  auth.users, auth.uid()/auth.role(), and Supabase's default privileges).
--  Supabase-managed objects (extensions, the platform's rls_auto_enable event
--  trigger) are intentionally not created here.
--
--  To change the schema: write a new numbered migration, then regenerate this
--  file with `npm --prefix tools/sync-harness run schema`.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Tables ──────────────────────────────────────────────────────────────────

create table public.acquisition_attribution (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  source       text,
  medium       text,
  campaign     text,
  content      text,
  term         text,
  fbclid       text,
  landing_path text,
  captured_at  timestamp with time zone,
  created_at   timestamp with time zone default now() not null
);

create table public.analytics_events (
  id         uuid default gen_random_uuid() not null,
  user_id    uuid,
  event_name text not null,
  project_id uuid,
  local_date date,
  metadata   jsonb,
  dedupe_key text,
  created_at timestamp with time zone default now() not null
);

create table public.analytics_excluded_users (
  user_id    uuid not null,
  reason     text,
  created_by uuid,
  created_at timestamp with time zone default now() not null
);

-- Ordered manuscript structure. Belongs to a Manuscript (manuscript_id); its
-- Project is manuscripts.project_id. Contains no prose.
create table public.chapters (
  id            uuid default gen_random_uuid() not null,
  manuscript_id uuid not null,
  title         text not null,
  position      integer not null,
  created_at    timestamp with time zone default now() not null,
  updated_at    timestamp with time zone default now() not null,
  is_completed  boolean default false
);

create table public.deleted_accounts (
  id                   uuid default gen_random_uuid() not null,
  original_user_id     uuid not null,
  email                text,
  username             text,
  display_name         text,
  xp                   integer,
  level                integer,
  subscription_tier    text,
  deleted_at           timestamp with time zone default now() not null,
  was_excluded_account boolean default false not null
);

create table public.founder_notes (
  id         uuid default gen_random_uuid() not null,
  author_id  uuid,
  content    text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.future_letters (
  id          uuid default gen_random_uuid() not null,
  user_id     uuid not null,
  project_id  uuid not null,
  content     text not null,
  created_at  timestamp with time zone default now() not null,
  reveal_at   timestamp with time zone default (now() + '1 year'::interval) not null,
  revealed_at timestamp with time zone
);

create table public.game_sessions (
  id               uuid default gen_random_uuid() not null,
  user_id          uuid not null,
  mode             text not null,
  words_written    integer default 0 not null,
  duration_seconds integer,
  xp_earned        integer default 0 not null,
  completed        boolean default false not null,
  created_at       timestamp with time zone default now() not null,
  enemy_type       text,
  meta             jsonb default '{}'::jsonb
);

create table public.game_tickets (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid,
  week_start   date not null,
  tickets_used integer default 0
);

-- Exactly one per Project (unique project_id), created by trg_project_manuscript
-- and deleted with the Project. Writers can read their own; nothing else.
create table public.manuscripts (
  id         uuid default gen_random_uuid() not null,
  project_id uuid not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.profiles (
  id                      uuid not null,
  username                text,
  display_name            text,
  avatar_url              text,
  xp                      integer default 0 not null,
  level                   integer default 1 not null,
  created_at              timestamp with time zone default now() not null,
  preferences             jsonb,
  stripe_customer_id      text,
  subscription_tier       text default 'free'::text,
  subscription_status     text default 'inactive'::text,
  subscription_price_id   text,
  subscription_period_end timestamp with time zone,
  has_written_first_words boolean default false not null,
  is_admin                boolean default false not null
);

create table public.project_notes (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid not null,
  content      text not null,
  is_completed boolean default false not null,
  is_pinned    boolean default false not null,
  created_at   timestamp with time zone default now() not null,
  completed_at timestamp with time zone,
  updated_at   timestamp with time zone default now() not null
);

create table public.projects (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  title        text not null,
  description  text,
  cover_color  text,
  word_count   integer default 0 not null,
  created_at   timestamp with time zone default now() not null,
  updated_at   timestamp with time zone default now() not null,
  chapter_goal integer,
  is_pinned    boolean default false not null
);

-- Manuscript prose. A Scene BELONGS to one Manuscript (manuscript_id, never
-- changes) and is PLACED in a Chapter of that Manuscript, or Unplaced when
-- chapter_id is null. There is no canonical Scene. Scene IDs are stable: a
-- future Rune 1.x migration keeps every Page ID as its Scene ID.
create table public.scenes (
  id            uuid default gen_random_uuid() not null,
  manuscript_id uuid not null,
  chapter_id    uuid,
  title         text not null,
  content       jsonb,
  word_count    integer default 0 not null,
  position      integer not null,
  version       integer default 1 not null,
  created_at    timestamp with time zone default now() not null,
  updated_at    timestamp with time zone default now() not null
);

create table public.schema_migrations (
  version     text not null,
  name        text not null,
  applied_at  timestamp with time zone,
  recorded_at timestamp with time zone default now() not null,
  note        text
);

-- NOTE: production shape (stripe_event_id NOT NULL, tier, status; no payload)
-- differs from migration 004 and from what the Stripe webhook inserts, so those
-- inserts currently fail. Carried over from the Rune 1.x baseline as-is.
create table public.subscription_events (
  id              uuid default gen_random_uuid() not null,
  user_id         uuid,
  stripe_event_id text not null,
  event_type      text not null,
  tier            text,
  status          text,
  created_at      timestamp with time zone default now()
);

create table public.user_pricing_entitlements (
  user_id                    uuid not null,
  pricing_cohort             text default 'starter_2k'::text not null,
  pricing_notice_resolved_at timestamp with time zone,
  founder_offer_status       text default 'not_offered'::text not null,
  founder_offer_claimed_at   timestamp with time zone,
  created_at                 timestamp with time zone default now() not null,
  updated_at                 timestamp with time zone default now() not null
);

create table public.user_unlockables (
  id            uuid default gen_random_uuid() not null,
  user_id       uuid not null,
  unlockable_id text not null,
  unlocked_at   timestamp with time zone default now() not null
);

create table public.writing_goals (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid,
  type         text not null,
  target_words integer not null,
  created_at   timestamp with time zone default now() not null
);

-- Typed-word writing activity. Editor rows are keyed per Scene (scene_id),
-- Arena and other rows have scene_id null; uniqueness is the partial unique
-- indexes below. Deleting a Scene deletes its rows (as in Rune 1.x).
create table public.writing_sessions (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid,
  scene_id     uuid,
  words_added  integer default 0 not null,
  session_date date default CURRENT_DATE not null,
  created_at   timestamp with time zone default now() not null
);

create table public.xp_events (
  id                uuid default gen_random_uuid() not null,
  user_id           uuid not null,
  amount            integer not null,
  reason            text not null,
  created_at        timestamp with time zone default now() not null,
  source_session_id uuid
);

-- ── Constraints ─────────────────────────────────────────────────────────────
alter table public.acquisition_attribution add constraint acquisition_attribution_pkey PRIMARY KEY (id);
alter table public.analytics_events add constraint analytics_events_pkey PRIMARY KEY (id);
alter table public.analytics_excluded_users add constraint analytics_excluded_users_pkey PRIMARY KEY (user_id);
alter table public.chapters add constraint chapters_pkey PRIMARY KEY (id);
alter table public.deleted_accounts add constraint deleted_accounts_pkey PRIMARY KEY (id);
alter table public.founder_notes add constraint founder_notes_pkey PRIMARY KEY (id);
alter table public.future_letters add constraint future_letters_pkey PRIMARY KEY (id);
alter table public.game_sessions add constraint game_sessions_pkey PRIMARY KEY (id);
alter table public.game_tickets add constraint game_tickets_pkey PRIMARY KEY (id);
alter table public.manuscripts add constraint manuscripts_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.project_notes add constraint project_notes_pkey PRIMARY KEY (id);
alter table public.projects add constraint projects_pkey PRIMARY KEY (id);
alter table public.scenes add constraint scenes_pkey PRIMARY KEY (id);
alter table public.schema_migrations add constraint schema_migrations_pkey PRIMARY KEY (version);
alter table public.subscription_events add constraint subscription_events_pkey PRIMARY KEY (id);
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_pkey PRIMARY KEY (user_id);
alter table public.user_unlockables add constraint user_unlockables_pkey PRIMARY KEY (id);
alter table public.writing_goals add constraint writing_goals_pkey PRIMARY KEY (id);
alter table public.writing_sessions add constraint writing_sessions_pkey PRIMARY KEY (id);
alter table public.xp_events add constraint xp_events_pkey PRIMARY KEY (id);
alter table public.acquisition_attribution add constraint acquisition_attribution_user_id_key UNIQUE (user_id);
alter table public.chapters add constraint chapters_id_manuscript_id_key UNIQUE (id, manuscript_id);
alter table public.game_tickets add constraint game_tickets_user_id_week_start_key UNIQUE (user_id, week_start);
alter table public.manuscripts add constraint manuscripts_project_id_key UNIQUE (project_id);
alter table public.profiles add constraint profiles_username_key UNIQUE (username);
alter table public.user_unlockables add constraint user_unlockables_user_id_unlockable_id_key UNIQUE (user_id, unlockable_id);
alter table public.profiles add constraint profiles_subscription_status_check CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'past_due'::text, 'canceled'::text]));
alter table public.profiles add constraint profiles_subscription_tier_check CHECK (subscription_tier = ANY (ARRAY['free'::text, 'scribe'::text, 'arcane'::text]));
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_founder_offer_status_check CHECK (founder_offer_status = ANY (ARRAY['not_offered'::text, 'eligible'::text, 'claimed'::text, 'declined'::text]));
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_pricing_cohort_check CHECK (pricing_cohort = ANY (ARRAY['legacy_15k'::text, 'starter_2k'::text]));
alter table public.writing_goals add constraint writing_goals_type_check CHECK (type = ANY (ARRAY['daily_global'::text, 'daily_project'::text, 'project_total'::text]));
alter table public.acquisition_attribution add constraint acquisition_attribution_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.analytics_events add constraint analytics_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.analytics_events add constraint analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.analytics_excluded_users add constraint analytics_excluded_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.analytics_excluded_users add constraint analytics_excluded_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.chapters add constraint chapters_manuscript_id_fkey FOREIGN KEY (manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE;
alter table public.founder_notes add constraint founder_notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.future_letters add constraint future_letters_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.future_letters add constraint future_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.game_sessions add constraint game_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.game_tickets add constraint game_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.manuscripts add constraint manuscripts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.project_notes add constraint project_notes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.project_notes add constraint project_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.projects add constraint projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.scenes add constraint scenes_chapter_same_manuscript_fkey FOREIGN KEY (chapter_id, manuscript_id) REFERENCES chapters(id, manuscript_id) ON DELETE CASCADE;
alter table public.scenes add constraint scenes_manuscript_id_fkey FOREIGN KEY (manuscript_id) REFERENCES manuscripts(id) ON DELETE CASCADE;
alter table public.subscription_events add constraint subscription_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.user_unlockables add constraint user_unlockables_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.writing_goals add constraint writing_goals_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.writing_goals add constraint writing_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_scene_id_fkey FOREIGN KEY (scene_id) REFERENCES scenes(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.xp_events add constraint xp_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX analytics_events_dedupe_idx ON public.analytics_events USING btree (user_id, event_name, dedupe_key);
CREATE INDEX analytics_events_name_created_idx ON public.analytics_events USING btree (event_name, created_at);
CREATE INDEX analytics_events_user_created_idx ON public.analytics_events USING btree (user_id, created_at);
CREATE INDEX chapters_manuscript_id_position_idx ON public.chapters USING btree (manuscript_id, "position");
CREATE INDEX profiles_stripe_customer_id_idx ON public.profiles USING btree (stripe_customer_id);
CREATE INDEX scenes_chapter_id_position_idx ON public.scenes USING btree (chapter_id, "position");
CREATE INDEX scenes_manuscript_id_idx ON public.scenes USING btree (manuscript_id);
CREATE INDEX user_pricing_entitlements_cohort_idx ON public.user_pricing_entitlements USING btree (pricing_cohort);
CREATE UNIQUE INDEX writing_sessions_null_project_unique ON public.writing_sessions USING btree (user_id, session_date) WHERE ((project_id IS NULL) AND (scene_id IS NULL));
CREATE UNIQUE INDEX writing_sessions_project_unique ON public.writing_sessions USING btree (user_id, project_id, session_date) WHERE ((project_id IS NOT NULL) AND (scene_id IS NULL));
CREATE UNIQUE INDEX writing_sessions_scene_unique ON public.writing_sessions USING btree (user_id, scene_id, session_date) WHERE (scene_id IS NOT NULL);

-- ── Functions ───────────────────────────────────────────────────────────────

-- Free-limit account total: EVERY Scene the caller owns, placed or Unplaced.
-- Not the ordered manuscript total (placed Scenes only). Never collapse them.
CREATE OR REPLACE FUNCTION public.account_word_total(p_candidate_scene_id uuid DEFAULT NULL::uuid, p_candidate_word_count integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_total int;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  with existing_scenes as (
    select
      case
        when p_candidate_scene_id is not null and s.id = p_candidate_scene_id
        then p_candidate_word_count
        else s.word_count
      end as word_count
    from public.scenes s
    join public.manuscripts m on m.id = s.manuscript_id
    join public.projects pr on pr.id = m.project_id
    where pr.user_id = auth.uid()
  ),
  new_scene as (
    -- Synthetic row for a brand-new Scene not yet inserted anywhere.
    select p_candidate_word_count as word_count
    where p_candidate_scene_id is null
      and p_candidate_word_count is not null
  )
  select coalesce(sum(word_count), 0)
  into v_total
  from (
    select word_count from existing_scenes
    union all
    select word_count from new_scene
  ) all_words;

  return v_total;
end;
$function$;

CREATE OR REPLACE FUNCTION public.bump_project_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  update public.projects
  set updated_at = now()
  where id = (
    select m.project_id
    from public.manuscripts m
    where m.id = new.manuscript_id
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.create_project_manuscript()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.manuscripts (project_id) values (new.id);
  return null;
end;
$function$;

CREATE OR REPLACE FUNCTION public.duplicate_project_checked(p_project_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_source public.projects%rowtype;
  v_source_manuscript_id uuid;
  v_source_chapter record;
  v_new_project public.projects%rowtype;
  v_new_manuscript_id uuid;
  v_new_chapter_id uuid;
  v_new_title text;
  v_used_numbers int[];
  v_draft_num int;
  v_source_total int;
  v_placed_total int;
  v_account_total int;
  v_limit int;
begin
  perform public.lock_account_word_budget();

  select * into v_source
    from public.projects
   where id = p_project_id and user_id = auth.uid();

  if not found then
    return jsonb_build_object('status', 'error', 'error', 'Project not found');
  end if;

  select m.id into v_source_manuscript_id
    from public.manuscripts m
   where m.project_id = p_project_id;

  select coalesce(sum(s.word_count), 0),
         coalesce(sum(s.word_count) filter (where s.chapter_id is not null), 0)
    into v_source_total, v_placed_total
    from public.scenes s
   where s.manuscript_id = v_source_manuscript_id;

  if v_source_total > 0 then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_account_total := public.account_word_total();
      if v_account_total + v_source_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  -- Unique "— Draft N" title: smallest unused number starting at 2 (gap-filling).
  select array_agg((regexp_match(p.title, '— Draft (\d+)$'))[1]::int)
    into v_used_numbers
  from public.projects p
  where p.user_id = auth.uid()
    and p.title ilike v_source.title || ' — Draft%'
    and regexp_match(p.title, '— Draft (\d+)$') is not null;

  v_draft_num := 2;
  while v_used_numbers is not null and v_draft_num = any(v_used_numbers) loop
    v_draft_num := v_draft_num + 1;
  end loop;

  v_new_title := v_source.title || ' — Draft ' || v_draft_num;

  insert into public.projects (user_id, title, description, cover_color, word_count)
  values (auth.uid(), v_new_title, v_source.description, v_source.cover_color, v_placed_total)
  returning * into v_new_project;

  -- Created by trg_project_manuscript.
  select m.id into v_new_manuscript_id
    from public.manuscripts m
   where m.project_id = v_new_project.id;

  for v_source_chapter in
    select * from public.chapters where manuscript_id = v_source_manuscript_id order by position
  loop
    insert into public.chapters (manuscript_id, title, position)
    values (v_new_manuscript_id, v_source_chapter.title, v_source_chapter.position)
    returning id into v_new_chapter_id;

    insert into public.scenes (manuscript_id, chapter_id, title, content, word_count, position)
    select v_new_manuscript_id, v_new_chapter_id, s.title, s.content, s.word_count, s.position
      from public.scenes s
     where s.chapter_id = v_source_chapter.id
     order by s.position;
  end loop;

  insert into public.scenes (manuscript_id, chapter_id, title, content, word_count, position)
  select v_new_manuscript_id, null, s.title, s.content, s.word_count, s.position
    from public.scenes s
   where s.manuscript_id = v_source_manuscript_id and s.chapter_id is null
   order by s.position;

  return jsonb_build_object('status', 'ok', 'project', to_jsonb(v_new_project));
end;
$function$;

CREATE OR REPLACE FUNCTION public.fill_scene_manuscript_id()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.manuscript_id is null and new.chapter_id is not null then
    select c.manuscript_id into new.manuscript_id
      from public.chapters c
     where c.id = new.chapter_id;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.forbid_manuscript_reassignment()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if new.manuscript_id is distinct from old.manuscript_id then
    raise exception 'A row of % cannot move to another Manuscript', tg_table_name
      using errcode = 'check_violation';
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.free_word_limit_for_caller()
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_tier text;
  v_cohort text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select subscription_tier into v_tier from public.profiles where id = auth.uid();
  if coalesce(v_tier, 'free') <> 'free' then
    return null;
  end if;

  select coalesce(pricing_cohort, 'starter_2k') into v_cohort
    from public.user_pricing_entitlements where user_id = auth.uid();

  return case coalesce(v_cohort, 'starter_2k')
    when 'legacy_15k' then 15000
    else 2000
  end;
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url,
    xp,
    level,
    has_written_first_words,
    subscription_tier
  ) values (
    new.id,
    new.raw_user_meta_data ->> 'display_name',
    new.raw_user_meta_data ->> 'avatar_url',
    0,
    1,
    false,
    'free'
  );

  insert into public.user_pricing_entitlements (
    user_id,
    pricing_cohort,
    founder_offer_status
  ) values (
    new.id,
    'starter_2k',
    'not_offered'
  );

  return new;
end;
$function$;

-- Unused by the app. SECURITY DEFINER without a pinned search_path, trusts
-- p_user_id, and is executable by PUBLIC/anon. Carried over from the Rune 1.x
-- baseline as-is; hardening is a separate, explicitly approved change.
CREATE OR REPLACE FUNCTION public.increment_game_ticket(p_user_id uuid, p_week_start date)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.game_tickets (user_id, week_start, tickets_used)
  VALUES (p_user_id, p_week_start, 1)
  ON CONFLICT (user_id, week_start)
  DO UPDATE SET tickets_used = game_tickets.tickets_used + 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.increment_scene_version()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  new.version = old.version + 1;
  new.updated_at = now(); -- server-side high-precision timestamp
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.insert_scene_checked(p_chapter_id uuid, p_title text, p_content jsonb, p_word_count integer, p_position integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_limit int;
  v_new_total int;
  v_new public.scenes%rowtype;
begin
  perform public.lock_account_word_budget();

  if p_word_count > 0 then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_new_total := public.account_word_total(null, p_word_count);
      if v_new_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  insert into public.scenes (chapter_id, title, content, word_count, position)
  values (p_chapter_id, p_title, p_content, p_word_count, p_position)
  returning * into v_new;

  return jsonb_build_object('status', 'ok', 'id', v_new.id);
end;
$function$;

CREATE OR REPLACE FUNCTION public.insert_unplaced_scene_checked(p_manuscript_id uuid, p_title text, p_content jsonb, p_word_count integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_limit int;
  v_new_total int;
  v_position int;
  v_new public.scenes%rowtype;
begin
  perform public.lock_account_word_budget();

  -- RLS: another writer's Manuscript is invisible.
  if not exists (select 1 from public.manuscripts m where m.id = p_manuscript_id) then
    return jsonb_build_object('status', 'error', 'error', 'Manuscript not found');
  end if;

  if p_word_count > 0 then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_new_total := public.account_word_total(null, p_word_count);
      if v_new_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  select coalesce(max(s.position) + 1, 0) into v_position
    from public.scenes s
   where s.manuscript_id = p_manuscript_id and s.chapter_id is null;

  insert into public.scenes (manuscript_id, chapter_id, title, content, word_count, position)
  values (p_manuscript_id, null, p_title, p_content, p_word_count, v_position)
  returning * into v_new;

  return jsonb_build_object('status', 'ok', 'id', v_new.id);
end;
$function$;

CREATE OR REPLACE FUNCTION public.lock_account_word_budget()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  perform pg_advisory_xact_lock(('x' || substr(md5(auth.uid()::text), 1, 16))::bit(64)::bigint);
end;
$function$;

CREATE OR REPLACE FUNCTION public.protect_billing_columns()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.role() = 'authenticated' then
    if new.subscription_tier is distinct from old.subscription_tier then
      new.subscription_tier := old.subscription_tier;
    end if;
    if new.subscription_status is distinct from old.subscription_status then
      new.subscription_status := old.subscription_status;
    end if;
    if new.subscription_price_id is distinct from old.subscription_price_id then
      new.subscription_price_id := old.subscription_price_id;
    end if;
    if new.subscription_period_end is distinct from old.subscription_period_end then
      new.subscription_period_end := old.subscription_period_end;
    end if;
    if new.stripe_customer_id is distinct from old.stripe_customer_id then
      new.stripe_customer_id := old.stripe_customer_id;
    end if;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.protect_is_admin()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if auth.role() = 'authenticated' and new.is_admin is distinct from old.is_admin then
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.reorder_chapter_scenes(p_chapter_id uuid, p_scene_ids uuid[])
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_current uuid[];
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  -- RLS: another writer's Chapter is invisible.
  if not exists (select 1 from public.chapters c where c.id = p_chapter_id) then
    return jsonb_build_object('status', 'error', 'error', 'Chapter not found');
  end if;

  -- Lock the Chapter's Scenes so a concurrent reorder or move-out waits.
  select coalesce(array_agg(s.id order by s.id), '{}')
    into v_current
    from (select id from public.scenes where chapter_id = p_chapter_id for update) s;

  if coalesce(array_length(p_scene_ids, 1), 0) <> coalesce(array_length(v_current, 1), 0)
     or (select count(distinct x) from unnest(p_scene_ids) x) <> coalesce(array_length(v_current, 1), 0)
     or not (p_scene_ids <@ v_current) then
    return jsonb_build_object('status', 'stale');
  end if;

  update public.scenes s
     set position = o.ord - 1
    from unnest(p_scene_ids) with ordinality as o(id, ord)
   where s.id = o.id
     and s.chapter_id = p_chapter_id
     and s.position is distinct from (o.ord - 1)::int;

  return jsonb_build_object('status', 'ok');
end;
$function$;

-- Save-path RPC. Statuses: ok | word_limit_blocked | version_mismatch | error
-- ('Scene not found'). Once clients depend on it, never overload or extend it.
CREATE OR REPLACE FUNCTION public.save_scene_checked(p_scene_id uuid, p_content jsonb, p_word_count integer, p_expected_version integer DEFAULT NULL::integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_old_word_count int;
  v_limit int;
  v_new_total int;
  v_updated public.scenes%rowtype;
begin
  perform public.lock_account_word_budget();

  select s.word_count
    into v_old_word_count
    from public.scenes s
    where s.id = p_scene_id;

  if not found then
    return jsonb_build_object('status', 'error', 'error', 'Scene not found');
  end if;

  -- Only enforce when words are being added — never block edits/deletions.
  -- A Scene that is already over the allowance is never trapped: shrinking
  -- or net-neutral edits always pass, only further growth is blocked.
  if p_word_count > v_old_word_count then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_new_total := public.account_word_total(p_scene_id, p_word_count);
      if v_new_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  if p_expected_version is not null then
    update public.scenes
       set content = p_content, word_count = p_word_count
     where id = p_scene_id and version = p_expected_version
     returning * into v_updated;

    if not found then
      return jsonb_build_object('status', 'version_mismatch');
    end if;
  else
    update public.scenes
       set content = p_content, word_count = p_word_count
     where id = p_scene_id
     returning * into v_updated;

    if not found then
      return jsonb_build_object('status', 'error', 'error', 'Scene not found');
    end if;
  end if;

  return jsonb_build_object(
    'status', 'ok',
    'updated_at', v_updated.updated_at,
    'version', v_updated.version
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.touch_pricing_entitlement_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- ── Function privileges (differences from Supabase defaults) ────────────────
revoke execute on function public.account_word_total(p_candidate_scene_id uuid, p_candidate_word_count integer) from public;
revoke execute on function public.account_word_total(p_candidate_scene_id uuid, p_candidate_word_count integer) from anon;
revoke execute on function public.duplicate_project_checked(p_project_id uuid) from public;
revoke execute on function public.free_word_limit_for_caller() from public;
revoke execute on function public.insert_scene_checked(p_chapter_id uuid, p_title text, p_content jsonb, p_word_count integer, p_position integer) from public;
revoke execute on function public.insert_scene_checked(p_chapter_id uuid, p_title text, p_content jsonb, p_word_count integer, p_position integer) from anon;
revoke execute on function public.insert_unplaced_scene_checked(p_manuscript_id uuid, p_title text, p_content jsonb, p_word_count integer) from public;
revoke execute on function public.insert_unplaced_scene_checked(p_manuscript_id uuid, p_title text, p_content jsonb, p_word_count integer) from anon;
revoke execute on function public.lock_account_word_budget() from public;
revoke execute on function public.reorder_chapter_scenes(p_chapter_id uuid, p_scene_ids uuid[]) from public;
revoke execute on function public.reorder_chapter_scenes(p_chapter_id uuid, p_scene_ids uuid[]) from anon;
revoke execute on function public.save_scene_checked(p_scene_id uuid, p_content jsonb, p_word_count integer, p_expected_version integer) from public;
revoke execute on function public.save_scene_checked(p_scene_id uuid, p_content jsonb, p_word_count integer, p_expected_version integer) from anon;

-- ── Table privileges (differences from Supabase defaults) ───────────────────
revoke delete, insert, references, select, trigger, truncate, update on public.schema_migrations from anon;
revoke delete, insert, references, select, trigger, truncate, update on public.schema_migrations from authenticated;

-- ── Row Level Security ──────────────────────────────────────────────────────
alter table public.acquisition_attribution enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_excluded_users enable row level security;
alter table public.chapters enable row level security;
alter table public.deleted_accounts enable row level security;
alter table public.founder_notes enable row level security;
alter table public.future_letters enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_tickets enable row level security;
alter table public.manuscripts enable row level security;
alter table public.profiles enable row level security;
alter table public.project_notes enable row level security;
alter table public.projects enable row level security;
alter table public.scenes enable row level security;
alter table public.schema_migrations enable row level security;
alter table public.subscription_events enable row level security;
alter table public.user_pricing_entitlements enable row level security;
alter table public.user_unlockables enable row level security;
alter table public.writing_goals enable row level security;
alter table public.writing_sessions enable row level security;
alter table public.xp_events enable row level security;
-- Tables with RLS enabled and no policy below are service-role only.

-- projects still carries the legacy "Users can manage their own projects" FOR
-- ALL policy beside its per-command policies (both permissive, OR-ed), as in
-- Rune 1.x. Manuscript tables use per-command policies for `authenticated` only.

create policy "chapters: delete own" on public.chapters
  as permissive for delete to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = chapters.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "chapters: insert own" on public.chapters
  as permissive for insert to authenticated
  with check ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = chapters.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "chapters: select own" on public.chapters
  as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = chapters.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "chapters: update own" on public.chapters
  as permissive for update to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = chapters.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = chapters.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "future_letters: delete own" on public.future_letters
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "future_letters: insert own" on public.future_letters
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "future_letters: select own" on public.future_letters
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "future_letters: update own" on public.future_letters
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "game_sessions: delete own" on public.game_sessions
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "game_sessions: insert own" on public.game_sessions
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "game_sessions: select own" on public.game_sessions
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "game_sessions: update own" on public.game_sessions
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "Users manage own tickets" on public.game_tickets
  as permissive for all to public
  using ((auth.uid() = user_id));

create policy "manuscripts: select own" on public.manuscripts
  as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM projects p
  WHERE ((p.id = manuscripts.project_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "profiles: select own" on public.profiles
  as permissive for select to public
  using ((auth.uid() = id));

create policy "profiles: update own" on public.profiles
  as permissive for update to public
  using ((auth.uid() = id));

create policy "project_notes: delete own" on public.project_notes
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "project_notes: insert own" on public.project_notes
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "project_notes: select own" on public.project_notes
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "project_notes: update own" on public.project_notes
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "projects: delete own" on public.projects
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "projects: insert own" on public.projects
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "projects: select own" on public.projects
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "projects: update own" on public.projects
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "Users can manage their own projects" on public.projects
  as permissive for all to public
  using ((auth.uid() = user_id));

create policy "scenes: delete own" on public.scenes
  as permissive for delete to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = scenes.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "scenes: insert own" on public.scenes
  as permissive for insert to authenticated
  with check ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = scenes.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "scenes: select own" on public.scenes
  as permissive for select to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = scenes.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "scenes: update own" on public.scenes
  as permissive for update to authenticated
  using ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = scenes.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))))
  with check ((EXISTS ( SELECT 1
   FROM (manuscripts m
     JOIN projects p ON ((p.id = m.project_id)))
  WHERE ((m.id = scenes.manuscript_id) AND (p.user_id = ( SELECT auth.uid() AS uid))))));

create policy "subscription_events: select own" on public.subscription_events
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "Users can view own events" on public.subscription_events
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "user_pricing_entitlements: select own" on public.user_pricing_entitlements
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "user_unlockables: insert own" on public.user_unlockables
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "Users can view their own unlockables" on public.user_unlockables
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "Users manage own goals" on public.writing_goals
  as permissive for all to public
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Users manage own writing sessions" on public.writing_sessions
  as permissive for all to public
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "xp_events: insert own" on public.xp_events
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "xp_events: select own" on public.xp_events
  as permissive for select to public
  using ((auth.uid() = user_id));

-- ── Triggers ────────────────────────────────────────────────────────────────
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER chapters_forbid_manuscript_reassignment BEFORE UPDATE OF manuscript_id ON chapters FOR EACH ROW EXECUTE FUNCTION forbid_manuscript_reassignment();
CREATE TRIGGER profiles_protect_billing_columns BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION protect_billing_columns();
CREATE TRIGGER profiles_protect_is_admin BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION protect_is_admin();
CREATE TRIGGER trg_project_manuscript AFTER INSERT ON projects FOR EACH ROW EXECUTE FUNCTION create_project_manuscript();
CREATE TRIGGER scene_version_trigger BEFORE UPDATE ON scenes FOR EACH ROW EXECUTE FUNCTION increment_scene_version();
CREATE TRIGGER scenes_fill_manuscript_id BEFORE INSERT ON scenes FOR EACH ROW EXECUTE FUNCTION fill_scene_manuscript_id();
CREATE TRIGGER scenes_forbid_manuscript_reassignment BEFORE UPDATE OF manuscript_id ON scenes FOR EACH ROW EXECUTE FUNCTION forbid_manuscript_reassignment();
CREATE TRIGGER trg_scene_updated AFTER UPDATE ON scenes FOR EACH ROW EXECUTE FUNCTION bump_project_updated_at();
CREATE TRIGGER user_pricing_entitlements_touch_updated_at BEFORE UPDATE ON user_pricing_entitlements FOR EACH ROW EXECUTE FUNCTION touch_pricing_entitlement_updated_at();

-- ── Migration ledger (migrations contained in this file) ────────────────────
insert into public.schema_migrations (version, name, applied_at, note) values
  ('000', 'production baseline 2026-09-24 (schema.sql)', null, 'Generated from the production catalog snapshot src/lib/supabase/catalog/production-2026-09-24.json. Fresh databases are built from schema.sql, then migrations 013+.'),
  ('001', '001_canonical_page.sql', null, 'historical — contained in the baseline; never re-run'),
  ('002', '002_word_goals.sql', null, 'historical — contained in the baseline; never re-run. Its unique(user_id, project_id, session_date) was later replaced in production by partial unique indexes.'),
  ('003', '003_chapter_completion.sql', null, 'historical — contained in the baseline; never re-run'),
  ('004', '004_billing.sql', null, 'historical — contained in the baseline; never re-run. Production subscription_events shape differs from this file.'),
  ('005', '005_game_tickets.sql', null, 'historical — contained in the baseline; never re-run'),
  ('006', '006_offline_sync.sql', null, 'historical — contained in the baseline; never re-run'),
  ('007', '007_fix_signup_trigger.sql', null, 'historical — SUPERSEDED by 009; re-running regresses handle_new_user'),
  ('008', '008_future_letters.sql', null, 'historical — contained in the baseline; never re-run'),
  ('009', '009_pricing_cohorts.sql', null, 'historical — contained in the baseline; never re-run (contains a one-time backfill)'),
  ('010', '010_analytics_excluded_users.sql', null, 'historical — contained in the baseline; never re-run'),
  ('011', '011_account_word_limit.sql', null, 'historical — contained in the baseline; never re-run'),
  ('012', '012_fix_bump_project_updated_at.sql', null, 'historical — contained in the baseline; never re-run'),
  ('013', '013_schema_migrations_ledger.sql', null, 'ledger created'),
  ('014', '014_assert_production_baseline.sql', null, 'baseline assertions passed: production-only columns, FK cascades, writing_sessions indexes, triggers, save-path RPC contracts, manuscript RLS policy set'),
  ('015', '015_rune2_manuscript_foundation.sql', null, 'Rune 2.0 manuscript foundation on an empty database: manuscripts, chapters.manuscript_id, scenes (replaces pages), writing_sessions.scene_id, Scene save RPCs, no canonical behavior'),
  ('016', '016_scene_structure_rpcs.sql', null, 'Rune 2.0 Scene structure: insert_unplaced_scene_checked (free-limit-checked Unplaced creation), reorder_chapter_scenes (atomic, validated Scene reorder)');
