#!/usr/bin/env node
// Generates the Rune 1.x production baseline from a committed production
// catalog snapshot (output of catalog.sql), so the legacy schema is derived
// from what production actually runs instead of being maintained by hand.
//
//   node tools/db-audit/generate-schema.mjs \
//     src/lib/supabase/catalog/production-2026-09-24.json \
//     src/lib/supabase/baseline/production-2026-09-24.sql
//
// The baseline is what production (Rune 1.x) runs. The canonical Rune 2.0
// schema, src/lib/supabase/schema.sql, is built from this baseline plus the
// migrations by tools/sync-harness/build-schema.mjs.
//
// The regression harness proves the baseline by loading it into Postgres,
// re-running catalog.sql, and diffing against the snapshot
// (tools/sync-harness/tests/schema-equivalence.test.mjs).
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import { loadCatalog } from './catalog-lib.mjs';
import { generateSchemaSql } from './schema-generator.mjs';

// Short explanations for objects whose purpose isn't obvious from their
// definition. History lives in the migrations; these are pointers.
export const PRODUCTION_NOTES = {
  pages: [
    'Manuscript prose. Compatibility-critical: stale clients and queued offline saves',
    'read id/content/word_count/version/updated_at/chapter_id directly, and Page IDs',
    'are IndexedDB keys. In Rune 2.0 this table stores Scenes; Page ID = Scene ID.',
  ],
  writing_sessions: [
    'Typed-word writing activity. Editor rows are keyed per page (page_id), Arena',
    'rows have page_id null. Uniqueness is enforced by the partial unique indexes',
    'below — the table-level unique(user_id, project_id, session_date) from',
    'migration 002 no longer exists in production. page_id cascades on page delete.',
  ],
  subscription_events: [
    'NOTE: production shape (stripe_event_id NOT NULL, tier, status; no payload)',
    'differs from migration 004 and from what the Stripe webhook inserts, so those',
    'inserts currently fail (table is empty). Recorded as-is; see catalog README.',
  ],
  'index:unique_user_page_date_idx': [
    'writing_sessions carries overlapping partial unique indexes in production',
    '(unique_user_page_date_idx ≈ writing_sessions_page_unique, and',
    'unique_user_project_date_null_page_idx ⊇ writing_sessions_project_unique).',
    'Recorded as-is; de-duplicating them is a separate change.',
  ],
  'fn:increment_game_ticket': [
    'Unused by the app. SECURITY DEFINER without a pinned search_path, trusts',
    'p_user_id, and is executable by PUBLIC/anon. Recorded as-is; hardening is a',
    'separate, explicitly approved change.',
  ],
  'fn:save_page_checked': [
    'Save-path RPC (migration 011). Signature, argument names, return shape and',
    'status values are a contract with stale clients — never overload or extend.',
  ],
  'policies:legacy': [
    'The unnamed-style "Users can manage …" FOR ALL policies on projects, chapters',
    'and pages predate the per-command "…: <cmd> own" policies. Both sets exist in',
    'production and are permissive (OR-ed). Any change to ownership rules must',
    'account for both.',
  ],
};

export function productionHeader(snapshotPath, cat) {
  return [
    'Rune — production schema baseline (GENERATED — do not edit by hand)',
    '',
    'Generated by tools/db-audit/generate-schema.mjs from',
    snapshotPath,
    `(production catalog captured ${cat.meta?.captured_at ?? 'unknown'}, PostgreSQL ${cat.meta?.server_version ?? '?'}).`,
    '',
    'This file is the `public` schema production actually runs, plus the',
    'auth.users signup trigger. It is the ONLY supported way to build a new',
    'database. Then apply every migration numbered 013 and above, in order.',
    'Migrations 001–012 are history — they are already contained here and must',
    'never be re-run against any database.',
    '',
    'Prerequisite: a Supabase project (roles anon/authenticated/service_role,',
    'auth.users, auth.uid()/auth.role(), and Supabase\'s default privileges).',
    'Supabase-managed objects (extensions, the platform\'s rls_auto_enable event',
    'trigger) are intentionally not created here.',
    '',
    'To change the schema: write a new numbered migration, apply it following',
    'tools/db-audit/STAGING.md, re-capture the catalog, and regenerate this',
    'file from the new snapshot.',
  ];
}

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const [, , snapshotArg, outArg] = process.argv;
  if (!snapshotArg || !outArg) {
    console.error('usage: generate-schema.mjs <catalog snapshot .json|.csv> <output .sql>');
    process.exit(2);
  }
  const cat = loadCatalog(snapshotArg);
  const { sql, stats } = generateSchemaSql(cat, {
    header: productionHeader(path.relative(process.cwd(), snapshotArg), cat),
    notes: PRODUCTION_NOTES,
  });
  fs.writeFileSync(outArg, sql);
  console.log(`wrote ${outArg}: ${stats.tables} tables, ${stats.constraints} constraints, ${stats.functions} functions, ${stats.policies} policies, ${stats.triggers} triggers`);
}
