#!/usr/bin/env node
// Generates src/lib/supabase/schema.sql from a committed production catalog
// snapshot (output of catalog.sql), so the fresh-install schema is derived
// from what production actually runs instead of being maintained by hand.
//
//   node tools/db-audit/generate-schema.mjs \
//     src/lib/supabase/catalog/production-2026-09-24.json \
//     src/lib/supabase/schema.sql
//
// Definitions (constraints, indexes, policies, triggers, functions) are
// emitted verbatim from the catalog. Grants are emitted only where
// production differs from what Supabase's default privileges produce for
// objects created by `postgres` in `public`: EXECUTE for PUBLIC plus
// postgres/anon/authenticated/service_role on functions, and all table
// privileges for anon/authenticated/service_role on tables. The regression
// harness proves the result by loading it into Postgres, re-running
// catalog.sql, and diffing against the snapshot
// (tools/sync-harness/tests/schema-equivalence.test.mjs).
import fs from 'node:fs';
import path from 'node:path';
import { loadCatalog, SUPABASE_MANAGED } from './catalog-lib.mjs';

const [, , snapshotArg, outArg] = process.argv;
if (!snapshotArg || !outArg) {
  console.error('usage: generate-schema.mjs <catalog snapshot .json|.csv> <output schema.sql>');
  process.exit(2);
}

const cat = loadCatalog(snapshotArg);
const q = (name) => (/^[a-z_][a-z0-9_]*$/.test(name) ? name : `"${name.replaceAll('"', '""')}"`);
const lines = [];
const emit = (...l) => lines.push(...l);
const rule = (title) => emit('', `-- ── ${title} ${'─'.repeat(Math.max(3, 72 - title.length))}`);

// Short explanations for objects whose purpose isn't obvious from their
// definition. History lives in the migrations; these are pointers.
const NOTES = {
  pages: [
    'Manuscript prose. Compatibility-critical: stale clients and queued offline saves',
    'read id/content/word_count/version/updated_at/chapter_id directly, and Page IDs',
    'are IndexedDB keys. In Rune 2.0 this table stores Scenes; Page ID = Scene ID.',
  ],
  writing_sessions: [
    'Typed-word writing activity. Editor rows are keyed per page (page_id), Arena',
    'rows have page_id null. Uniqueness is enforced by the partial unique indexes',
    'below — the table-level unique(user_id, project_id, session_date) from',
    'migration 002 no longer exists in production. page_id cascades on page delete.',
  ],
  subscription_events: [
    'NOTE: production shape (stripe_event_id NOT NULL, tier, status; no payload)',
    'differs from migration 004 and from what the Stripe webhook inserts, so those',
    'inserts currently fail (table is empty). Recorded as-is; see catalog README.',
  ],
  'fn:increment_game_ticket': [
    'Unused by the app. SECURITY DEFINER without a pinned search_path, trusts',
    'p_user_id, and is executable by PUBLIC/anon. Recorded as-is; hardening is a',
    'separate, explicitly approved change.',
  ],
  'fn:save_page_checked': [
    'Save-path RPC (migration 011). Signature, argument names, return shape and',
    'status values are a contract with stale clients — never overload or extend.',
  ],
  'policies:legacy': [
    'The unnamed-style "Users can manage …" FOR ALL policies on projects, chapters',
    'and pages predate the per-command "…: <cmd> own" policies. Both sets exist in',
    'production and are permissive (OR-ed). Any change to ownership rules must',
    'account for both.',
  ],
};
const note = (key) => (NOTES[key] ?? []).forEach((l) => emit(`-- ${l}`));

// ── header ──
emit(
  '-- ═══════════════════════════════════════════════════════════════════════════',
  '--  Rune — production schema baseline (GENERATED — do not edit by hand)',
  '-- ═══════════════════════════════════════════════════════════════════════════',
  '--',
  `--  Generated by tools/db-audit/generate-schema.mjs from`,
  `--  ${path.relative(process.cwd(), snapshotArg)}`,
  `--  (production catalog captured ${cat.meta?.captured_at ?? 'unknown'}, PostgreSQL ${cat.meta?.server_version ?? '?'}).`,
  '--',
  '--  This file is the `public` schema production actually runs, plus the',
  '--  auth.users signup trigger. It is the ONLY supported way to build a new',
  '--  database. Then apply every migration numbered 013 and above, in order.',
  '--  Migrations 001–012 are history — they are already contained here and must',
  '--  never be re-run against any database.',
  '--',
  '--  Prerequisite: a Supabase project (roles anon/authenticated/service_role,',
  '--  auth.users, auth.uid()/auth.role(), and Supabase\'s default privileges).',
  '--  Supabase-managed objects (extensions, the platform\'s rls_auto_enable event',
  '--  trigger) are intentionally not created here.',
  '--',
  '--  To change the schema: write a new numbered migration, apply it following',
  '--  tools/db-audit/STAGING.md, re-capture the catalog, and regenerate this',
  '--  file from the new snapshot.',
  '-- ═══════════════════════════════════════════════════════════════════════════',
);

// ── tables ──
const tables = cat.relations.filter((r) => r.kind === 'table').map((r) => r.table).sort();
const colsBy = new Map(tables.map((t) => [t, []]));
for (const c of cat.columns) if (colsBy.has(c.table)) colsBy.get(c.table).push(c);

rule('Tables');
for (const t of tables) {
  emit('');
  note(t);
  const cols = colsBy.get(t).sort((a, b) => a.ord - b.ord);
  const width = Math.max(...cols.map((c) => c.column.length));
  emit(`create table public.${q(t)} (`);
  cols.forEach((c, i) => {
    if (c.identity || c.generated) throw new Error(`generator: identity/generated column ${t}.${c.column} not supported`);
    const parts = [q(c.column).padEnd(width), c.type];
    if (c.default !== null && c.default !== undefined) parts.push(`default ${c.default}`);
    if (c.not_null) parts.push('not null');
    emit(`  ${parts.join(' ')}${i < cols.length - 1 ? ',' : ''}`);
  });
  emit(');');
}

// ── constraints: primary/unique/check first, then foreign keys ──
rule('Constraints');
const order = { primary_key: 0, unique: 1, check: 2, exclusion: 3, foreign_key: 4 };
const cons = [...cat.constraints].sort((a, b) => order[a.type] - order[b.type] || a.table.localeCompare(b.table) || a.name.localeCompare(b.name));
for (const c of cons) {
  if (c.validated === false) throw new Error(`generator: NOT VALID constraint ${c.name} not supported`);
  emit(`alter table public.${q(c.table)} add constraint ${q(c.name)} ${c.definition};`);
}

// ── indexes not backing a constraint ──
rule('Indexes');
const consNames = new Set(cat.constraints.map((c) => c.name));
for (const i of [...cat.indexes].sort((a, b) => a.table.localeCompare(b.table) || a.name.localeCompare(b.name))) {
  if (consNames.has(i.name)) continue;
  if (i.table === 'writing_sessions' && i.name === 'unique_user_page_date_idx') {
    emit('-- writing_sessions carries overlapping partial unique indexes in production',
      '-- (unique_user_page_date_idx ≈ writing_sessions_page_unique, and',
      '-- unique_user_project_date_null_page_idx ⊇ writing_sessions_project_unique).',
      '-- Recorded as-is; de-duplicating them is a separate change.');
  }
  emit(`${i.definition};`);
}

// ── functions ──
rule('Functions');
const fns = cat.functions
  .filter((f) => !SUPABASE_MANAGED.functions.has(f.name))
  .sort((a, b) => a.name.localeCompare(b.name) || a.identity_args.localeCompare(b.identity_args));
for (const f of fns) {
  if (f.definition_redacted || !f.definition) throw new Error(`generator: definition of ${f.name} is redacted — obtain it separately`);
  emit('');
  note(`fn:${f.name}`);
  emit(`${f.definition.trim()};`);
}

// ── function EXECUTE privileges that differ from Supabase defaults ──
const DEFAULT_FN_GRANTEES = ['PUBLIC', 'anon', 'authenticated', 'postgres', 'service_role'];
const fnAclLines = [];
for (const f of fns) {
  const have = new Set((f.acl ?? '').replace(/^\{|\}$/g, '').split(',').filter(Boolean)
    .filter((e) => e.split('=')[1]?.split('/')[0].includes('X'))
    .map((e) => e.split('=')[0] || 'PUBLIC'));
  if (f.acl_is_default) continue; // null ACL == Postgres default (PUBLIC execute)
  const sig = `public.${q(f.name)}(${f.identity_args})`;
  for (const g of DEFAULT_FN_GRANTEES) if (!have.has(g)) fnAclLines.push(`revoke execute on function ${sig} from ${g === 'PUBLIC' ? 'public' : g};`);
  for (const g of have) if (!DEFAULT_FN_GRANTEES.includes(g)) fnAclLines.push(`grant execute on function ${sig} to ${g};`);
}
if (fnAclLines.length) {
  rule('Function privileges (differences from Supabase defaults)');
  emit(...fnAclLines);
}

// ── table privileges that differ from Supabase defaults ──
const TABLE_PRIVS = ['DELETE', 'INSERT', 'REFERENCES', 'SELECT', 'TRIGGER', 'TRUNCATE', 'UPDATE'];
const API_ROLES = ['anon', 'authenticated', 'service_role'];
const tableAclLines = [];
for (const t of tables) {
  for (const role of API_ROLES) {
    const have = new Set(cat.table_grants.filter((g) => g.table === t && g.grantee === role).map((g) => g.privilege));
    const missing = TABLE_PRIVS.filter((p) => !have.has(p));
    if (missing.length) tableAclLines.push(`revoke ${missing.join(', ').toLowerCase()} on public.${q(t)} from ${role};`);
  }
}
if (tableAclLines.length) {
  rule('Table privileges (differences from Supabase defaults)');
  emit(...tableAclLines);
}

// ── row level security + policies ──
rule('Row Level Security');
for (const r of cat.relations.filter((x) => x.kind === 'table').sort((a, b) => a.table.localeCompare(b.table))) {
  if (r.rls_enabled) emit(`alter table public.${q(r.table)} enable row level security;`);
  if (r.rls_forced) emit(`alter table public.${q(r.table)} force row level security;`);
}
emit('-- Tables with RLS enabled and no policy below are service-role only.');
emit('');
note('policies:legacy');
const CMD = { ALL: 'all', SELECT: 'select', INSERT: 'insert', UPDATE: 'update', DELETE: 'delete' };
for (const p of [...cat.policies].sort((a, b) => a.table.localeCompare(b.table) || a.name.localeCompare(b.name))) {
  const roles = (p.roles ?? ['public']).map((r) => (r === 'public' ? 'public' : q(r))).join(', ');
  let sql = `create policy "${p.name.replaceAll('"', '""')}" on public.${q(p.table)}\n  as ${p.permissive.toLowerCase()} for ${CMD[p.command]} to ${roles}`;
  if (p.using) sql += `\n  using (${p.using})`;
  if (p.with_check) sql += `\n  with check (${p.with_check})`;
  emit('', `${sql};`);
}

// ── triggers ──
rule('Triggers');
for (const t of [...cat.triggers].sort((a, b) => a.table.localeCompare(b.table) || a.name.localeCompare(b.name))) {
  if (t.definition_redacted || !t.definition) throw new Error(`generator: trigger ${t.name} definition redacted — obtain it separately`);
  if (t.enabled !== 'O') throw new Error(`generator: trigger ${t.name} has non-default enabled state ${t.enabled}`);
  emit(`${t.definition};`);
}

emit('');
fs.writeFileSync(outArg, lines.join('\n'));
console.log(`wrote ${outArg}: ${tables.length} tables, ${cons.length} constraints, ${fns.length} functions, ${cat.policies.length} policies, ${cat.triggers.length} triggers`);
