// PGlite test database helpers: a fresh in-memory Postgres per test file,
// with the Supabase shim loaded first, and helpers to run SQL as a specific
// Supabase role/user the same way PostgREST does per request.
import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import path from 'node:path';

export const HARNESS_DIR = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
export const REPO_DIR = path.resolve(HARNESS_DIR, '../..');

/** The Rune 1.x production baseline (generated from the production catalog). Legacy tests load this. */
export const LEGACY_BASELINE = 'src/lib/supabase/baseline/production-2026-09-24.sql';
/** The canonical Rune 2.0 schema (generated by build-schema.mjs from the baseline + migrations). */
export const RUNE2_SCHEMA = 'src/lib/supabase/schema.sql';

/** Reads a file relative to the repository root. */
export function readRepoFile(relPath) {
  return fs.readFileSync(path.join(REPO_DIR, relPath), 'utf8');
}

/** Reads a committed migration by file name, e.g. '011_account_word_limit.sql'. */
export function readMigration(fileName) {
  return readRepoFile(`src/lib/supabase/migrations/${fileName}`);
}

/**
 * Creates a fresh PGlite database with the Supabase shim applied
 * (roles anon/authenticated/service_role, auth.users, auth.uid()/role()/jwt(),
 * Supabase default privileges on `public`).
 */
export async function createTestDb() {
  const db = new PGlite();
  await db.exec(fs.readFileSync(path.join(HARNESS_DIR, 'sql/supabase-shim.sql'), 'utf8'));
  return db;
}

function claimsSql(role, userId) {
  const sub = userId ?? '';
  const claims = JSON.stringify(userId ? { sub: userId, role } : { role });
  return (
    `select set_config('request.jwt.claim.sub', '${sub}', true),` +
    ` set_config('request.jwt.claim.role', '${role}', true),` +
    ` set_config('request.jwt.claims', '${claims.replaceAll("'", "''")}', true);`
  );
}

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const ROLES = new Set(['anon', 'authenticated', 'service_role']);

/**
 * Runs `fn(tx)` inside one transaction as the given Supabase role and user —
 * mirroring a single PostgREST request: `set local role` + request.jwt.*
 * claims, all discarded when the transaction ends. If `fn` throws, the
 * transaction rolls back and the error propagates.
 */
export async function withRole(db, { role = 'authenticated', userId = null } = {}, fn) {
  if (!ROLES.has(role)) throw new Error(`withRole: unknown role ${role}`);
  if (userId !== null && !UUID_RE.test(userId)) throw new Error(`withRole: invalid user id ${userId}`);
  return db.transaction(async (tx) => {
    await tx.exec(`set local role ${role}; ${claimsSql(role, userId)}`);
    return fn(tx);
  });
}

/** Shorthand: run as an authenticated user. */
export function asUser(db, userId, fn) {
  return withRole(db, { role: 'authenticated', userId }, fn);
}

/** Inserts an auth.users row (as the loading superuser), firing any auth trigger. */
export async function createAuthUser(db, id, meta = {}) {
  await db.query(`insert into auth.users (id, raw_user_meta_data) values ($1, $2)`, [id, meta]);
  return id;
}
