-- ═══════════════════════════════════════════════════════════════════════════
--  Rune — production schema baseline (GENERATED — do not edit by hand)
-- ═══════════════════════════════════════════════════════════════════════════
--
--  Generated by tools/db-audit/generate-schema.mjs from
--  src/lib/supabase/catalog/production-2026-09-24.json
--  (production catalog captured 2026-09-24T11:35:03.319548+00:00, PostgreSQL 17.6).
--
--  This file is the `public` schema production actually runs, plus the
--  auth.users signup trigger. It is the ONLY supported way to build a new
--  database. Then apply every migration numbered 013 and above, in order.
--  Migrations 001–012 are history — they are already contained here and must
--  never be re-run against any database.
--
--  Prerequisite: a Supabase project (roles anon/authenticated/service_role,
--  auth.users, auth.uid()/auth.role(), and Supabase's default privileges).
--  Supabase-managed objects (extensions, the platform's rls_auto_enable event
--  trigger) are intentionally not created here.
--
--  To change the schema: write a new numbered migration, apply it following
--  tools/db-audit/STAGING.md, re-capture the catalog, and regenerate this
--  file from the new snapshot.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Tables ──────────────────────────────────────────────────────────────────

create table public.acquisition_attribution (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  source       text,
  medium       text,
  campaign     text,
  content      text,
  term         text,
  fbclid       text,
  landing_path text,
  captured_at  timestamp with time zone,
  created_at   timestamp with time zone default now() not null
);

create table public.analytics_events (
  id         uuid default gen_random_uuid() not null,
  user_id    uuid,
  event_name text not null,
  project_id uuid,
  local_date date,
  metadata   jsonb,
  dedupe_key text,
  created_at timestamp with time zone default now() not null
);

create table public.analytics_excluded_users (
  user_id    uuid not null,
  reason     text,
  created_by uuid,
  created_at timestamp with time zone default now() not null
);

create table public.chapters (
  id           uuid default gen_random_uuid() not null,
  project_id   uuid not null,
  title        text not null,
  position     integer not null,
  created_at   timestamp with time zone default now() not null,
  updated_at   timestamp with time zone default now() not null,
  is_completed boolean default false
);

create table public.deleted_accounts (
  id                   uuid default gen_random_uuid() not null,
  original_user_id     uuid not null,
  email                text,
  username             text,
  display_name         text,
  xp                   integer,
  level                integer,
  subscription_tier    text,
  deleted_at           timestamp with time zone default now() not null,
  was_excluded_account boolean default false not null
);

create table public.founder_notes (
  id         uuid default gen_random_uuid() not null,
  author_id  uuid,
  content    text not null,
  created_at timestamp with time zone default now() not null,
  updated_at timestamp with time zone default now() not null
);

create table public.future_letters (
  id          uuid default gen_random_uuid() not null,
  user_id     uuid not null,
  project_id  uuid not null,
  content     text not null,
  created_at  timestamp with time zone default now() not null,
  reveal_at   timestamp with time zone default (now() + '1 year'::interval) not null,
  revealed_at timestamp with time zone
);

create table public.game_sessions (
  id               uuid default gen_random_uuid() not null,
  user_id          uuid not null,
  mode             text not null,
  words_written    integer default 0 not null,
  duration_seconds integer,
  xp_earned        integer default 0 not null,
  completed        boolean default false not null,
  created_at       timestamp with time zone default now() not null,
  enemy_type       text,
  meta             jsonb default '{}'::jsonb
);

create table public.game_tickets (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid,
  week_start   date not null,
  tickets_used integer default 0
);

-- Manuscript prose. Compatibility-critical: stale clients and queued offline saves
-- read id/content/word_count/version/updated_at/chapter_id directly, and Page IDs
-- are IndexedDB keys. In Rune 2.0 this table stores Scenes; Page ID = Scene ID.
create table public.pages (
  id           uuid default gen_random_uuid() not null,
  chapter_id   uuid not null,
  title        text not null,
  content      jsonb,
  word_count   integer default 0 not null,
  position     integer not null,
  created_at   timestamp with time zone default now() not null,
  updated_at   timestamp with time zone default now() not null,
  is_canonical boolean default false not null,
  version      integer default 1 not null
);

create table public.profiles (
  id                      uuid not null,
  username                text,
  display_name            text,
  avatar_url              text,
  xp                      integer default 0 not null,
  level                   integer default 1 not null,
  created_at              timestamp with time zone default now() not null,
  preferences             jsonb,
  stripe_customer_id      text,
  subscription_tier       text default 'free'::text,
  subscription_status     text default 'inactive'::text,
  subscription_price_id   text,
  subscription_period_end timestamp with time zone,
  has_written_first_words boolean default false not null,
  is_admin                boolean default false not null
);

create table public.project_notes (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid not null,
  content      text not null,
  is_completed boolean default false not null,
  is_pinned    boolean default false not null,
  created_at   timestamp with time zone default now() not null,
  completed_at timestamp with time zone,
  updated_at   timestamp with time zone default now() not null
);

create table public.projects (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  title        text not null,
  description  text,
  cover_color  text,
  word_count   integer default 0 not null,
  created_at   timestamp with time zone default now() not null,
  updated_at   timestamp with time zone default now() not null,
  chapter_goal integer,
  is_pinned    boolean default false not null
);

-- NOTE: production shape (stripe_event_id NOT NULL, tier, status; no payload)
-- differs from migration 004 and from what the Stripe webhook inserts, so those
-- inserts currently fail (table is empty). Recorded as-is; see catalog README.
create table public.subscription_events (
  id              uuid default gen_random_uuid() not null,
  user_id         uuid,
  stripe_event_id text not null,
  event_type      text not null,
  tier            text,
  status          text,
  created_at      timestamp with time zone default now()
);

create table public.user_pricing_entitlements (
  user_id                    uuid not null,
  pricing_cohort             text default 'starter_2k'::text not null,
  pricing_notice_resolved_at timestamp with time zone,
  founder_offer_status       text default 'not_offered'::text not null,
  founder_offer_claimed_at   timestamp with time zone,
  created_at                 timestamp with time zone default now() not null,
  updated_at                 timestamp with time zone default now() not null
);

create table public.user_unlockables (
  id            uuid default gen_random_uuid() not null,
  user_id       uuid not null,
  unlockable_id text not null,
  unlocked_at   timestamp with time zone default now() not null
);

create table public.writing_goals (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid,
  type         text not null,
  target_words integer not null,
  created_at   timestamp with time zone default now() not null
);

-- Typed-word writing activity. Editor rows are keyed per page (page_id), Arena
-- rows have page_id null. Uniqueness is enforced by the partial unique indexes
-- below — the table-level unique(user_id, project_id, session_date) from
-- migration 002 no longer exists in production. page_id cascades on page delete.
create table public.writing_sessions (
  id           uuid default gen_random_uuid() not null,
  user_id      uuid not null,
  project_id   uuid,
  words_added  integer default 0 not null,
  session_date date default CURRENT_DATE not null,
  created_at   timestamp with time zone default now() not null,
  page_id      uuid
);

create table public.xp_events (
  id                uuid default gen_random_uuid() not null,
  user_id           uuid not null,
  amount            integer not null,
  reason            text not null,
  created_at        timestamp with time zone default now() not null,
  source_session_id uuid
);

-- ── Constraints ─────────────────────────────────────────────────────────────
alter table public.acquisition_attribution add constraint acquisition_attribution_pkey PRIMARY KEY (id);
alter table public.analytics_events add constraint analytics_events_pkey PRIMARY KEY (id);
alter table public.analytics_excluded_users add constraint analytics_excluded_users_pkey PRIMARY KEY (user_id);
alter table public.chapters add constraint chapters_pkey PRIMARY KEY (id);
alter table public.deleted_accounts add constraint deleted_accounts_pkey PRIMARY KEY (id);
alter table public.founder_notes add constraint founder_notes_pkey PRIMARY KEY (id);
alter table public.future_letters add constraint future_letters_pkey PRIMARY KEY (id);
alter table public.game_sessions add constraint game_sessions_pkey PRIMARY KEY (id);
alter table public.game_tickets add constraint game_tickets_pkey PRIMARY KEY (id);
alter table public.pages add constraint pages_pkey PRIMARY KEY (id);
alter table public.profiles add constraint profiles_pkey PRIMARY KEY (id);
alter table public.project_notes add constraint project_notes_pkey PRIMARY KEY (id);
alter table public.projects add constraint projects_pkey PRIMARY KEY (id);
alter table public.subscription_events add constraint subscription_events_pkey PRIMARY KEY (id);
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_pkey PRIMARY KEY (user_id);
alter table public.user_unlockables add constraint user_unlockables_pkey PRIMARY KEY (id);
alter table public.writing_goals add constraint writing_goals_pkey PRIMARY KEY (id);
alter table public.writing_sessions add constraint writing_sessions_pkey PRIMARY KEY (id);
alter table public.xp_events add constraint xp_events_pkey PRIMARY KEY (id);
alter table public.acquisition_attribution add constraint acquisition_attribution_user_id_key UNIQUE (user_id);
alter table public.game_tickets add constraint game_tickets_user_id_week_start_key UNIQUE (user_id, week_start);
alter table public.profiles add constraint profiles_username_key UNIQUE (username);
alter table public.user_unlockables add constraint user_unlockables_user_id_unlockable_id_key UNIQUE (user_id, unlockable_id);
alter table public.profiles add constraint profiles_subscription_status_check CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'past_due'::text, 'canceled'::text]));
alter table public.profiles add constraint profiles_subscription_tier_check CHECK (subscription_tier = ANY (ARRAY['free'::text, 'scribe'::text, 'arcane'::text]));
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_founder_offer_status_check CHECK (founder_offer_status = ANY (ARRAY['not_offered'::text, 'eligible'::text, 'claimed'::text, 'declined'::text]));
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_pricing_cohort_check CHECK (pricing_cohort = ANY (ARRAY['legacy_15k'::text, 'starter_2k'::text]));
alter table public.writing_goals add constraint writing_goals_type_check CHECK (type = ANY (ARRAY['daily_global'::text, 'daily_project'::text, 'project_total'::text]));
alter table public.acquisition_attribution add constraint acquisition_attribution_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.analytics_events add constraint analytics_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.analytics_events add constraint analytics_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.analytics_excluded_users add constraint analytics_excluded_users_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.analytics_excluded_users add constraint analytics_excluded_users_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.chapters add constraint chapters_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.founder_notes add constraint founder_notes_author_id_fkey FOREIGN KEY (author_id) REFERENCES profiles(id) ON DELETE SET NULL;
alter table public.future_letters add constraint future_letters_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.future_letters add constraint future_letters_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.game_sessions add constraint game_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.game_tickets add constraint game_tickets_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.pages add constraint pages_chapter_id_fkey FOREIGN KEY (chapter_id) REFERENCES chapters(id) ON DELETE CASCADE;
alter table public.profiles add constraint profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.project_notes add constraint project_notes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.project_notes add constraint project_notes_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.projects add constraint projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.subscription_events add constraint subscription_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;
alter table public.user_pricing_entitlements add constraint user_pricing_entitlements_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.user_unlockables add constraint user_unlockables_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.writing_goals add constraint writing_goals_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.writing_goals add constraint writing_goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_page_id_fkey FOREIGN KEY (page_id) REFERENCES pages(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE;
alter table public.writing_sessions add constraint writing_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;
alter table public.xp_events add constraint xp_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE;

-- ── Indexes ─────────────────────────────────────────────────────────────────
CREATE UNIQUE INDEX analytics_events_dedupe_idx ON public.analytics_events USING btree (user_id, event_name, dedupe_key);
CREATE INDEX analytics_events_name_created_idx ON public.analytics_events USING btree (event_name, created_at);
CREATE INDEX analytics_events_user_created_idx ON public.analytics_events USING btree (user_id, created_at);
CREATE INDEX profiles_stripe_customer_id_idx ON public.profiles USING btree (stripe_customer_id);
CREATE INDEX user_pricing_entitlements_cohort_idx ON public.user_pricing_entitlements USING btree (pricing_cohort);
-- writing_sessions carries overlapping partial unique indexes in production
-- (unique_user_page_date_idx ≈ writing_sessions_page_unique, and
-- unique_user_project_date_null_page_idx ⊇ writing_sessions_project_unique).
-- Recorded as-is; de-duplicating them is a separate change.
CREATE UNIQUE INDEX unique_user_page_date_idx ON public.writing_sessions USING btree (user_id, session_date, page_id) WHERE (page_id IS NOT NULL);
CREATE UNIQUE INDEX unique_user_project_date_null_page_idx ON public.writing_sessions USING btree (user_id, session_date, project_id) WHERE (page_id IS NULL);
CREATE UNIQUE INDEX writing_sessions_null_project_unique ON public.writing_sessions USING btree (user_id, session_date) WHERE ((project_id IS NULL) AND (page_id IS NULL));
CREATE UNIQUE INDEX writing_sessions_page_unique ON public.writing_sessions USING btree (user_id, page_id, session_date) WHERE (page_id IS NOT NULL);
CREATE UNIQUE INDEX writing_sessions_project_unique ON public.writing_sessions USING btree (user_id, project_id, session_date) WHERE ((project_id IS NOT NULL) AND (page_id IS NULL));

-- ── Functions ───────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.account_word_total(p_candidate_page_id uuid DEFAULT NULL::uuid, p_candidate_word_count integer DEFAULT NULL::integer)
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_total int;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  with existing_pages as (
    select
      p.id as page_id,
      case
        when p_candidate_page_id is not null and p.id = p_candidate_page_id
        then p_candidate_word_count
        else p.word_count
      end as word_count
    from public.chapters c
    join public.projects pr on pr.id = c.project_id
    join public.pages p on p.chapter_id = c.id
    where pr.user_id = auth.uid()
  ),
  new_page as (
    -- Synthetic row for a brand-new page not yet inserted anywhere.
    select p_candidate_word_count as word_count
    where p_candidate_page_id is null
      and p_candidate_word_count is not null
  )
  select coalesce(sum(word_count), 0)
  into v_total
  from (
    select word_count from existing_pages
    union all
    select word_count from new_page
  ) all_words;

  return v_total;
end;
$function$;

CREATE OR REPLACE FUNCTION public.bump_project_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  update public.projects
  set updated_at = now()
  where id = (
    select c.project_id
    from public.chapters c
    where c.id = new.chapter_id
  );

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.duplicate_project_checked(p_project_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_source public.projects%rowtype;
  v_source_chapter record;
  v_source_page record;
  v_new_project public.projects%rowtype;
  v_new_chapter_id uuid;
  v_new_title text;
  v_used_numbers int[];
  v_draft_num int;
  v_source_total int;
  v_account_total int;
  v_limit int;
begin
  perform public.lock_account_word_budget();

  select * into v_source
    from public.projects
   where id = p_project_id and user_id = auth.uid();

  if not found then
    return jsonb_build_object('status', 'error', 'error', 'Project not found');
  end if;

  -- Every page in the source project, canonical or not — the same
  -- all-pages definition account_word_total() uses, see the migration
  -- header above for why. Computed directly here since the source project
  -- already exists and needs no substitution.
  select coalesce(sum(p.word_count), 0)
    into v_source_total
  from public.chapters c
  join public.pages p on p.chapter_id = c.id
  where c.project_id = p_project_id;

  if v_source_total > 0 then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_account_total := public.account_word_total();
      if v_account_total + v_source_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  -- Unique "— Draft N" title: smallest unused number starting at 2,
  -- preserving the exact gap-filling behavior of the prior JS
  -- implementation (not simply max+1). regexp_match() (singular) is a
  -- plain scalar function returning text[] or null — not a set-returning
  -- function, so it's called directly rather than via a LATERAL join.
  select array_agg((regexp_match(p.title, '— Draft (\d+)$'))[1]::int)
    into v_used_numbers
  from public.projects p
  where p.user_id = auth.uid()
    and p.title ilike v_source.title || ' — Draft%'
    and regexp_match(p.title, '— Draft (\d+)$') is not null;

  v_draft_num := 2;
  while v_used_numbers is not null and v_draft_num = any(v_used_numbers) loop
    v_draft_num := v_draft_num + 1;
  end loop;

  v_new_title := v_source.title || ' — Draft ' || v_draft_num;

  insert into public.projects (user_id, title, description, cover_color, word_count)
  values (auth.uid(), v_new_title, v_source.description, v_source.cover_color, v_source_total)
  returning * into v_new_project;

  for v_source_chapter in
    select * from public.chapters where project_id = p_project_id order by position
  loop
    insert into public.chapters (project_id, title, position)
    values (v_new_project.id, v_source_chapter.title, v_source_chapter.position)
    returning id into v_new_chapter_id;

    for v_source_page in
      select * from public.pages where chapter_id = v_source_chapter.id order by position
    loop
      insert into public.pages (chapter_id, title, content, word_count, position, is_canonical)
      values (
        v_new_chapter_id,
        v_source_page.title,
        v_source_page.content,
        v_source_page.word_count,
        v_source_page.position,
        v_source_page.is_canonical
      );
    end loop;
  end loop;

  return jsonb_build_object('status', 'ok', 'project', to_jsonb(v_new_project));
end;
$function$;

CREATE OR REPLACE FUNCTION public.enforce_single_canonical_page()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  update public.pages
  set is_canonical = false
  where chapter_id = new.chapter_id
    and id <> new.id
    and is_canonical = true;
  return null;
end;
$function$;

CREATE OR REPLACE FUNCTION public.free_word_limit_for_caller()
 RETURNS integer
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare
  v_tier text;
  v_cohort text;
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  select subscription_tier into v_tier from public.profiles where id = auth.uid();
  if coalesce(v_tier, 'free') <> 'free' then
    return null;
  end if;

  select coalesce(pricing_cohort, 'starter_2k') into v_cohort
    from public.user_pricing_entitlements where user_id = auth.uid();

  return case coalesce(v_cohort, 'starter_2k')
    when 'legacy_15k' then 15000
    else 2000
  end;
end;
$function$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.profiles (
    id,
    display_name,
    avatar_url,
    xp,
    level,
    has_written_first_words,
    subscription_tier
  ) values (
    new.id,
    new.raw_user_meta_data ->> 'display_name',
    new.raw_user_meta_data ->> 'avatar_url',
    0,
    1,
    false,
    'free'
  );

  insert into public.user_pricing_entitlements (
    user_id,
    pricing_cohort,
    founder_offer_status
  ) values (
    new.id,
    'starter_2k',
    'not_offered'
  );

  return new;
end;
$function$;

-- Unused by the app. SECURITY DEFINER without a pinned search_path, trusts
-- p_user_id, and is executable by PUBLIC/anon. Recorded as-is; hardening is a
-- separate, explicitly approved change.
CREATE OR REPLACE FUNCTION public.increment_game_ticket(p_user_id uuid, p_week_start date)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
  INSERT INTO public.game_tickets (user_id, week_start, tickets_used)
  VALUES (p_user_id, p_week_start, 1)
  ON CONFLICT (user_id, week_start)
  DO UPDATE SET tickets_used = game_tickets.tickets_used + 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.increment_page_version()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
BEGIN
  NEW.version = OLD.version + 1;
  NEW.updated_at = now(); -- Genrates a high-precision timestamptz locally on the Postgres server
  RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION public.insert_page_checked(p_chapter_id uuid, p_title text, p_content jsonb, p_word_count integer, p_position integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_limit int;
  v_new_total int;
  v_new public.pages%rowtype;
begin
  perform public.lock_account_word_budget();

  if p_word_count > 0 then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_new_total := public.account_word_total(null, p_word_count);
      if v_new_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  insert into public.pages (chapter_id, title, content, word_count, position, is_canonical)
  values (p_chapter_id, p_title, p_content, p_word_count, p_position, false)
  returning * into v_new;

  return jsonb_build_object('status', 'ok', 'id', v_new.id);
end;
$function$;

CREATE OR REPLACE FUNCTION public.lock_account_word_budget()
 RETURNS void
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
begin
  if auth.uid() is null then
    raise exception 'Not authenticated';
  end if;

  perform pg_advisory_xact_lock(('x' || substr(md5(auth.uid()::text), 1, 16))::bit(64)::bigint);
end;
$function$;

CREATE OR REPLACE FUNCTION public.protect_billing_columns()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  if auth.role() = 'authenticated' then
    if new.subscription_tier is distinct from old.subscription_tier then
      new.subscription_tier := old.subscription_tier;
    end if;
    if new.subscription_status is distinct from old.subscription_status then
      new.subscription_status := old.subscription_status;
    end if;
    if new.subscription_price_id is distinct from old.subscription_price_id then
      new.subscription_price_id := old.subscription_price_id;
    end if;
    if new.subscription_period_end is distinct from old.subscription_period_end then
      new.subscription_period_end := old.subscription_period_end;
    end if;
    if new.stripe_customer_id is distinct from old.stripe_customer_id then
      new.stripe_customer_id := old.stripe_customer_id;
    end if;
  end if;
  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.protect_is_admin()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  if auth.role() = 'authenticated' and new.is_admin is distinct from old.is_admin then
    new.is_admin := old.is_admin;
  end if;
  return new;
end;
$function$;

-- Save-path RPC (migration 011). Signature, argument names, return shape and
-- status values are a contract with stale clients — never overload or extend.
CREATE OR REPLACE FUNCTION public.save_page_checked(p_page_id uuid, p_content jsonb, p_word_count integer, p_expected_version integer DEFAULT NULL::integer)
 RETURNS jsonb
 LANGUAGE plpgsql
 SET search_path TO ''
AS $function$
declare
  v_old_word_count int;
  v_limit int;
  v_new_total int;
  v_updated public.pages%rowtype;
begin
  perform public.lock_account_word_budget();

  select p.word_count
    into v_old_word_count
    from public.pages p
    where p.id = p_page_id;

  if not found then
    return jsonb_build_object('status', 'error', 'error', 'Page not found');
  end if;

  -- Only enforce when words are being added — never block edits/deletions.
  -- A page that's already over the allowance (legacy data, a prior
  -- inconsistency) is never trapped: shrinking or net-neutral edits always
  -- pass, only further growth is blocked.
  if p_word_count > v_old_word_count then
    v_limit := public.free_word_limit_for_caller();
    if v_limit is not null then
      v_new_total := public.account_word_total(p_page_id, p_word_count);
      if v_new_total > v_limit then
        return jsonb_build_object('status', 'word_limit_blocked', 'limit', v_limit);
      end if;
    end if;
  end if;

  if p_expected_version is not null then
    update public.pages
       set content = p_content, word_count = p_word_count
     where id = p_page_id and version = p_expected_version
     returning * into v_updated;

    if not found then
      return jsonb_build_object('status', 'version_mismatch');
    end if;
  else
    update public.pages
       set content = p_content, word_count = p_word_count
     where id = p_page_id
     returning * into v_updated;

    if not found then
      return jsonb_build_object('status', 'error', 'error', 'Page not found');
    end if;
  end if;

  return jsonb_build_object(
    'status', 'ok',
    'updated_at', v_updated.updated_at,
    'version', v_updated.version
  );
end;
$function$;

CREATE OR REPLACE FUNCTION public.touch_pricing_entitlement_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

-- ── Function privileges (differences from Supabase defaults) ────────────────
revoke execute on function public.account_word_total(p_candidate_page_id uuid, p_candidate_word_count integer) from public;
revoke execute on function public.duplicate_project_checked(p_project_id uuid) from public;
revoke execute on function public.free_word_limit_for_caller() from public;
revoke execute on function public.insert_page_checked(p_chapter_id uuid, p_title text, p_content jsonb, p_word_count integer, p_position integer) from public;
revoke execute on function public.lock_account_word_budget() from public;
revoke execute on function public.save_page_checked(p_page_id uuid, p_content jsonb, p_word_count integer, p_expected_version integer) from public;

-- ── Row Level Security ──────────────────────────────────────────────────────
alter table public.acquisition_attribution enable row level security;
alter table public.analytics_events enable row level security;
alter table public.analytics_excluded_users enable row level security;
alter table public.chapters enable row level security;
alter table public.deleted_accounts enable row level security;
alter table public.founder_notes enable row level security;
alter table public.future_letters enable row level security;
alter table public.game_sessions enable row level security;
alter table public.game_tickets enable row level security;
alter table public.pages enable row level security;
alter table public.profiles enable row level security;
alter table public.project_notes enable row level security;
alter table public.projects enable row level security;
alter table public.subscription_events enable row level security;
alter table public.user_pricing_entitlements enable row level security;
alter table public.user_unlockables enable row level security;
alter table public.writing_goals enable row level security;
alter table public.writing_sessions enable row level security;
alter table public.xp_events enable row level security;
-- Tables with RLS enabled and no policy below are service-role only.

-- The unnamed-style "Users can manage …" FOR ALL policies on projects, chapters
-- and pages predate the per-command "…: <cmd> own" policies. Both sets exist in
-- production and are permissive (OR-ed). Any change to ownership rules must
-- account for both.

create policy "chapters: delete own" on public.chapters
  as permissive for delete to public
  using ((EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = chapters.project_id) AND (projects.user_id = auth.uid())))));

create policy "chapters: insert own" on public.chapters
  as permissive for insert to public
  with check ((EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = chapters.project_id) AND (projects.user_id = auth.uid())))));

create policy "chapters: select own" on public.chapters
  as permissive for select to public
  using ((EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = chapters.project_id) AND (projects.user_id = auth.uid())))));

create policy "chapters: update own" on public.chapters
  as permissive for update to public
  using ((EXISTS ( SELECT 1
   FROM projects
  WHERE ((projects.id = chapters.project_id) AND (projects.user_id = auth.uid())))));

create policy "Users can manage chapters of their projects" on public.chapters
  as permissive for all to public
  using ((project_id IN ( SELECT projects.id
   FROM projects
  WHERE (projects.user_id = auth.uid()))));

create policy "future_letters: delete own" on public.future_letters
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "future_letters: insert own" on public.future_letters
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "future_letters: select own" on public.future_letters
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "future_letters: update own" on public.future_letters
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "game_sessions: delete own" on public.game_sessions
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "game_sessions: insert own" on public.game_sessions
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "game_sessions: select own" on public.game_sessions
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "game_sessions: update own" on public.game_sessions
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "Users manage own tickets" on public.game_tickets
  as permissive for all to public
  using ((auth.uid() = user_id));

create policy "pages: delete own" on public.pages
  as permissive for delete to public
  using ((EXISTS ( SELECT 1
   FROM (chapters
     JOIN projects ON ((projects.id = chapters.project_id)))
  WHERE ((chapters.id = pages.chapter_id) AND (projects.user_id = auth.uid())))));

create policy "pages: insert own" on public.pages
  as permissive for insert to public
  with check ((EXISTS ( SELECT 1
   FROM (chapters
     JOIN projects ON ((projects.id = chapters.project_id)))
  WHERE ((chapters.id = pages.chapter_id) AND (projects.user_id = auth.uid())))));

create policy "pages: select own" on public.pages
  as permissive for select to public
  using ((EXISTS ( SELECT 1
   FROM (chapters
     JOIN projects ON ((projects.id = chapters.project_id)))
  WHERE ((chapters.id = pages.chapter_id) AND (projects.user_id = auth.uid())))));

create policy "pages: update own" on public.pages
  as permissive for update to public
  using ((EXISTS ( SELECT 1
   FROM (chapters
     JOIN projects ON ((projects.id = chapters.project_id)))
  WHERE ((chapters.id = pages.chapter_id) AND (projects.user_id = auth.uid())))));

create policy "Users can manage pages in their chapters" on public.pages
  as permissive for all to public
  using ((chapter_id IN ( SELECT c.id
   FROM (chapters c
     JOIN projects p ON ((c.project_id = p.id)))
  WHERE (p.user_id = auth.uid()))));

create policy "profiles: select own" on public.profiles
  as permissive for select to public
  using ((auth.uid() = id));

create policy "profiles: update own" on public.profiles
  as permissive for update to public
  using ((auth.uid() = id));

create policy "project_notes: delete own" on public.project_notes
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "project_notes: insert own" on public.project_notes
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "project_notes: select own" on public.project_notes
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "project_notes: update own" on public.project_notes
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "projects: delete own" on public.projects
  as permissive for delete to public
  using ((auth.uid() = user_id));

create policy "projects: insert own" on public.projects
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "projects: select own" on public.projects
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "projects: update own" on public.projects
  as permissive for update to public
  using ((auth.uid() = user_id));

create policy "Users can manage their own projects" on public.projects
  as permissive for all to public
  using ((auth.uid() = user_id));

create policy "subscription_events: select own" on public.subscription_events
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "Users can view own events" on public.subscription_events
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "user_pricing_entitlements: select own" on public.user_pricing_entitlements
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "user_unlockables: insert own" on public.user_unlockables
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "Users can view their own unlockables" on public.user_unlockables
  as permissive for select to public
  using ((auth.uid() = user_id));

create policy "Users manage own goals" on public.writing_goals
  as permissive for all to public
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "Users manage own writing sessions" on public.writing_sessions
  as permissive for all to public
  using ((auth.uid() = user_id))
  with check ((auth.uid() = user_id));

create policy "xp_events: insert own" on public.xp_events
  as permissive for insert to public
  with check ((auth.uid() = user_id));

create policy "xp_events: select own" on public.xp_events
  as permissive for select to public
  using ((auth.uid() = user_id));

-- ── Triggers ────────────────────────────────────────────────────────────────
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();
CREATE TRIGGER enforce_single_canonical AFTER UPDATE OF is_canonical ON pages FOR EACH ROW WHEN (new.is_canonical = true) EXECUTE FUNCTION enforce_single_canonical_page();
CREATE TRIGGER page_version_trigger BEFORE UPDATE ON pages FOR EACH ROW EXECUTE FUNCTION increment_page_version();
CREATE TRIGGER trg_page_updated AFTER UPDATE ON pages FOR EACH ROW EXECUTE FUNCTION bump_project_updated_at();
CREATE TRIGGER profiles_protect_billing_columns BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION protect_billing_columns();
CREATE TRIGGER profiles_protect_is_admin BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION protect_is_admin();
CREATE TRIGGER user_pricing_entitlements_touch_updated_at BEFORE UPDATE ON user_pricing_entitlements FOR EACH ROW EXECUTE FUNCTION touch_pricing_entitlement_updated_at();
